
# ================================
#  SEEDS
# ================================
seeds:
  - name: team_name
    description: "Seed file mapping team abbreviations to full team names."
    columns:
      - name: team_abbreviation
        description: "Three-letter team code."
        tests:
          - not_null
          - unique
      - name: team_name
        description: "Full team name."

# ================================
#  STAGING MODELS
# ================================
models:
  - name: stg_fact_nba_player_stats
    description: "Stage and clean raw NBA player performance data."
    columns:
      - name: player_id
        tests:
          - not_null
          - unique
      - name: team_id
        tests:
          - not_null
      - name: points
        description: "Average player points per game."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              
      - name: rebounds
        description: "Average player rebounds per game."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: stg_dim_nba_players
    description: "Stage player attributes from raw source."
    columns:
      - name: player_id
        tests:
          - not_null
          - unique
      - name: player_name
        description: "Full player name."

  - name: stg_dim_nba_teams
    description: "Stage NBA team information."
    columns:
      - name: team_id
        tests:
          - not_null
          - unique
      - name: team_abbreviation
        description: "Three-letter team code."

  - name: stg_dim_coaches
    description: "Stage NBA coach data."
    columns:
      - name: coach_id
        tests:
          - not_null
          - unique
      - name: team_id
        description: "Foreign key to team."
      - name: coach_name
        description: "Coach name."

# ================================
#  INTERMEDIATE MODELS
# ================================
  - name: int_incremental_player_stats
    description: "Incremental model joining players, teams, and coaches with performance stats."
    columns:
      - name: player_id
        tests: 
         - not_null
      - name: team_id
        tests: 
         - not_null

  - name: int_stats_per_min
    description: "Intermediate model calculating player impact per minute."
    columns:
      - name: player_impact_score
        description: "{{ doc('player_impact_score') }}"

  - name: int_team
    description: "Intermediate model joining player stats with team names from seed."
    columns:
      - name: team_name
        description: "Full team name from seed."

# ================================
#  MARTS
# ================================
  - name: mart_final
    description: "Team-level performance summary mart table."
    columns:
      - name: team_name
        description: "NBA team name."
      - name: total_players
        description: "Number of players in team."
      - name: avg_player_impact
        description: "Average player efficiency per team."
      - name: avg_total_points
        description: "Total team points scored."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: avg_total_rebounds
        description: "Total rebounds for the team."


# ================================
#  SNAPSHOT
# ================================
snapshots:
  - name: fact_nba_player_stats_snapshot
    description: "Snapshot tracking player performance changes over time (SCD Type 2)."
    columns:
      - name: player_id
        description: "Primary key for snapshot."
      - name: loaded_at
        description: "Record load timestamp."
