-- use account admin role
USE ROLE ACCOUNTADMIN;

-- create db, schema, and wh engine
CREATE DATABASE IF NOT EXISTS NBA_DB;
CREATE SCHEMA IF NOT EXISTS NBA_SCHEMA;
CREATE WAREHOUSE IF NOT EXISTS NBA_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 30;
    
-- create a dedicated role for dbt
CREATE ROLE IF NOT EXISTS DBT_ROLE;
    
-- create user
CREATE USER IF NOT EXISTS DBT_USER
  PASSWORD = ''
  LOGIN_NAME = 'dbt'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE = 'NBA_WH'
  DEFAULT_ROLE = 'DBT_ROLE'
  DEFAULT_NAMESPACE = 'NBA_DB.NBA_SCHEMA'
  COMMENT = 'FOR DATA MODELING AND TRANSFORMATIONS';

-- grant role to user
GRANT ROLE DBT_ROLE TO USER DBT_USER;
GRANT ROLE DBT_ROLE TO ROLE ACCOUNTADMIN;

-- grant privelages to role
USE DATABASE NBA_DB;
USE SCHEMA NBA_SCHEMA;
GRANT USAGE ON DATABASE NBA_DB TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA NBA_SCHEMA TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE NBA_WH TO ROLE DBT_ROLE;


-- set up permissions to role dbt_role
GRANT ALL ON WAREHOUSE NBA_WH TO ROLE DBT_ROLE; 
GRANT ALL ON DATABASE NBA_DB TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE NBA_DB to ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NBA_DB to ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NBA_SCHEMA to ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NBA_SCHEMA to ROLE DBT_ROLE;
GRANT TRUNCATE ON ALL TABLES IN SCHEMA NBA_DB.NBA_SCHEMA TO ROLE DBT_ROLE;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA NBA_DB.NBA_SCHEMA TO ROLE DBT_ROLE;

-- create stage 
CREATE OR REPLACE STAGE NBA_STAGE
url = ''
CREDENTIALS = (AWS_KEY_ID='' AWS_SECRET_KEY='')
file_format = (type = 'csv');
GRANT USAGE ON STAGE NBA_STAGE TO ROLE DBT_ROLE;

-- SuperSet Privelages
-- Use an admin role
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS REPORTER;
CREATE USER IF NOT EXISTS PRESET
PASSWORD=''
LOGIN_NAME='PRESET'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE='NBA_WH'
DEFAULT_ROLE='REPORTER'
DEFAULT_NAMESPACE='NBA.DEV'
COMMENT='Preset user for creating reports';
GRANT ROLE REPORTER TO USER PRESET;
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN;
GRANT ALL ON WAREHOUSE NBA_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE NBA_DB TO ROLE REPORTER;
GRANT USAGE ON SCHEMA NBA_SCHEMA TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA NBA_SCHEMA TO ROLE REPORTER;
GRANT SELECT ON ALL VIEWS IN SCHEMA NBA_SCHEMA TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NBA_SCHEMA TO ROLE REPORTER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NBA_SCHEMA TO ROLE REPORTER;

CREATE OR REPLACE NETWORK POLICY PRESET_POLICY
  ALLOWED_IP_LIST = (
    '35.161.45.11',
    '54.244.23.85',
    '52.32.136.54'
  )
  BLOCKED_IP_LIST = ();

ALTER USER PRESET SET NETWORK_POLICY = PRESET_POLICY;
